### ISSUE TITLE
Migrate LeaderElection to Lease API

### ISSUE THREAD

**Issue by aojea** [openshift/library-go#1178]
Upstream has done it for the controller manager and scheduler
https://github.com/kubernetes/kubernetes/issues/80289

should we do it here too?

https://github.com/openshift/library-go/blob/965974e0af3f9fb43ac3b33bc9e67c1cbfd16a0a/pkg/config/leaderelection/leaderelection.go#L53

it comes with some upgrade problems thought

**Comment by deezy30** [comment]
[adamsexotics32]()

**Comment by mprahl** [comment]
This PR doesn't change the default but it makes the leader election resource lock type configurable:
https://github.com/openshift/library-go/pull/1448
