### ISSUE TITLE
ApplyValidatingWebhookConfiguration does not work

### ISSUE THREAD

**Issue by jsafrane** [openshift/library-go#953]
There are couple of issues in ApplyValidatingWebhookConfiguration introduced in https://github.com/openshift/library-go/pull/902 

1. When used in the `StaticController`, `ApplyDirectly` fails with:
    ```E1130 17:41:41.847063   99786 base_controller.go:250] "StaticResourceController" controller failed to sync "key", err: 
    "webhook_configuration.yaml" (string): cannot decode "webhook_configuration.yaml": no kind "ValidatingWebhookConfiguration" 
    is registered for version "admissionregistration.k8s.io/v1" in scheme "pkg/runtime/scheme.go:101"
    ```
    This can be fixed by registering admission/v1 API around these parts: https://github.com/openshift/library-go/blob/bd449d1e2e25157fc0e304e0d5fcd239a2a7ff36/pkg/operator/resource/resourceapply/generic.go#L32-L33

---

2. `ApplyValidatingWebhookConfiguration` itself fails on updating a webhook config with:
    ```
    validatingwebhookconfigurations.admissionregistration.k8s.io "snapshot.storage.k8s.io" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
    ```
    It fails because the function tries to call `Update()` with `required`:
    https://github.com/openshift/library-go/blob/bd449d1e2e25157fc0e304e0d5fcd239a2a7ff36/pkg/operator/resource/resourceapply/admissions.go#L43
    All the other `Apply*` functions merge `required` and `existingCopy` to make sure all the metadata is there...

---

3. Change detection in `ApplyValidatingWebhookConfiguration` does not work at all. In OpenShift, it's common that an admission plugin injects the actual `caBundle` into `webhooks.clientConfig`. Therefore, the `required.webhooks` and `existingCopy.webhooks` will never be the same and the function will *always* update the `ValidatingWebhookConfiguration` object.
    https://github.com/openshift/library-go/blob/bd449d1e2e25157fc0e304e0d5fcd239a2a7ff36/pkg/operator/resource/resourceapply/admissions.go#L34-L37

@qiujian16, is the `ApplyValidatingWebhookConfiguration` used anywhere? How did you test it?

**Comment by qiujian16** [comment]
Sorry, the code is moved from here https://github.com/open-cluster-management/registration-operator/blob/master/pkg/helpers/helpers.go#L202-L227 where I miss some part.... 

For issue 1 & 2, I will fix it. But I do not have a good answer for issue 3, will we be able to know from webhook configuration when the cabundle will be injected?
